spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_listing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true

server:
  port: 9091

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka