spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/food_delivery.restaurant_listing
        username: postgres
        password: postgres

eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
